### ISSUE TITLE
virtual readS16 failed - need to throw refill/invalid

### ISSUE THREAD

**Issue by mrcmunir** [hulkholden/n64js#2]
Hello Great emulator :-)

I jump in the Super Mario64 go to Open Door in the first world but not continue because crash.

http://i49.tinypic.com/eqpao2.jpg 

0x802d5d9c: virtual readS16 failed - need to throw refill/invalid

**Comment by hulkholden** [comment]
(10 years pass :)

I made a whole bunch of changes, live at https://hulkholden.github.io/n64js/.

Most/all of the emulation issues with SM64 should be fixed now.
