### ISSUE TITLE
I'm way to many problems with lag

### ISSUE THREAD

**Issue by OldAccountWithDeadName** [hulkholden/n64js#6]
Super Mario 64 Boots Up at 30 to 60 then gets to mario head 7487 then it's super laggy from there?

Any way To Fix?

**Comment by hulkholden** [comment]
(10 years pass).

I've made a bunch of changes recently (live at https://hulkholden.github.io/n64js/). The head is still a little laggy but due to the relentless march of time performance should be a lot better all round.
