### ISSUE TITLE
SRAM, how to implement?

### ISSUE THREAD

**Issue by laurac8r** [hulkholden/n64js#9]
Hi I am getting this issue in the web gui for a certain game:

Warning! Unhandled savegame type: SRAM.

Just curious, is there a timeline for implementation of certain features?

**Comment by hulkholden** [comment]
This is implemented at head now (see e.g https://github.com/hulkholden/n64js/commit/e909c6cf9e09970bc0d21ff8c482d179632b09ae and https://github.com/hulkholden/n64js/commit/16788e05b04db7f14e679e632a32baf19f020409). 

It's not live at https://hulkholden.github.io/n64js/ yet. I'll look at doing a release sometime soon as there are lots of other fixes queued up.

**Comment by hulkholden** [comment]
This is live at https://hulkholden.github.io/n64js/ now.
